"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class abvcontrol_info_t(object):
    __slots__ = ["utime", "Hdg_Torque", "Sog_Thrust", "Tport", "Tstbd"]

    def __init__(self):
        self.utime = 0
        self.Hdg_Torque = 0.0
        self.Sog_Thrust = 0.0
        self.Tport = 0.0
        self.Tstbd = 0.0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(abvcontrol_info_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qffff", self.utime, self.Hdg_Torque, self.Sog_Thrust, self.Tport, self.Tstbd))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != abvcontrol_info_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return abvcontrol_info_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = abvcontrol_info_t()
        self.utime, self.Hdg_Torque, self.Sog_Thrust, self.Tport, self.Tstbd = struct.unpack(">qffff", buf.read(24))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if abvcontrol_info_t in parents: return 0
        tmphash = (0xf331d87483360060) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if abvcontrol_info_t._packed_fingerprint is None:
            abvcontrol_info_t._packed_fingerprint = struct.pack(">Q", abvcontrol_info_t._get_hash_recursive([]))
        return abvcontrol_info_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

