"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class ascii_t(object):
    __slots__ = ["utime", "str"]

    def __init__(self):
        self.utime = 0
        self.str = ""

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(ascii_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        __str_encoded = self.str.encode('utf-8')
        buf.write(struct.pack('>I', len(__str_encoded)+1))
        buf.write(__str_encoded)
        buf.write("\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != ascii_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ascii_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ascii_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        __str_len = struct.unpack('>I', buf.read(4))[0]
        self.str = buf.read(__str_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ascii_t in parents: return 0
        tmphash = (0xea923cbcf3c53360) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ascii_t._packed_fingerprint is None:
            ascii_t._packed_fingerprint = struct.pack(">Q", ascii_t._get_hash_recursive([]))
        return ascii_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

