"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class att_gps_t(object):
    __slots__ = ["utime", "tt", "lat", "lon", "sog"]

    def __init__(self):
        self.utime = 0
        self.tt = 0.0
        self.lat = 0.0
        self.lon = 0.0
        self.sog = 0.0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(att_gps_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qdfff", self.utime, self.tt, self.lat, self.lon, self.sog))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != att_gps_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return att_gps_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = att_gps_t()
        self.utime, self.tt, self.lat, self.lon, self.sog = struct.unpack(">qdfff", buf.read(28))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if att_gps_t in parents: return 0
        tmphash = (0xf6418655273e5554) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if att_gps_t._packed_fingerprint is None:
            att_gps_t._packed_fingerprint = struct.pack(">Q", att_gps_t._get_hash_recursive([]))
        return att_gps_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

