"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class att_os5000_t(object):
    __slots__ = ["utime", "roll", "pitch", "hdg", "T", "depth"]

    def __init__(self):
        self.utime = 0
        self.roll = 0.0
        self.pitch = 0.0
        self.hdg = 0.0
        self.T = 0.0
        self.depth = 0.0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(att_os5000_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qddddd", self.utime, self.roll, self.pitch, self.hdg, self.T, self.depth))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != att_os5000_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return att_os5000_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = att_os5000_t()
        self.utime, self.roll, self.pitch, self.hdg, self.T, self.depth = struct.unpack(">qddddd", buf.read(48))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if att_os5000_t in parents: return 0
        tmphash = (0xbd4db1b2c40b041a) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if att_os5000_t._packed_fingerprint is None:
            att_os5000_t._packed_fingerprint = struct.pack(">Q", att_os5000_t._get_hash_recursive([]))
        return att_os5000_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

