"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class button_event_t(object):
    __slots__ = ["utime", "on_off", "button"]

    def __init__(self):
        self.utime = 0
        self.on_off = False
        self.button = 0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(button_event_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qbh", self.utime, self.on_off, self.button))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != button_event_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return button_event_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = button_event_t()
        self.utime, self.on_off, self.button = struct.unpack(">qbh", buf.read(11))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if button_event_t in parents: return 0
        tmphash = (0x89dc7eac57c6f4d1) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if button_event_t._packed_fingerprint is None:
            button_event_t._packed_fingerprint = struct.pack(">Q", button_event_t._get_hash_recursive([]))
        return button_event_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

