"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class digitalin_t(object):
    __slots__ = ["utime", "digitals"]

    def __init__(self):
        self.utime = 0
        self.digitals = [ False for dim0 in range(8) ]

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(digitalin_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(struct.pack('>8b', *self.digitals[:8]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != digitalin_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return digitalin_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = digitalin_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.digitals = struct.unpack('>8b', buf.read(8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if digitalin_t in parents: return 0
        tmphash = (0x493ae6ad93627536) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if digitalin_t._packed_fingerprint is None:
            digitalin_t._packed_fingerprint = struct.pack(">Q", digitalin_t._get_hash_recursive([]))
        return digitalin_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

