"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class doxygen_t(object):
    __slots__ = ["utime", "temp", "concentration", "airsaturation"]

    def __init__(self):
        self.utime = 0
        self.temp = 0.0
        self.concentration = 0.0
        self.airsaturation = 0.0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(doxygen_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qfff", self.utime, self.temp, self.concentration, self.airsaturation))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != doxygen_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return doxygen_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = doxygen_t()
        self.utime, self.temp, self.concentration, self.airsaturation = struct.unpack(">qfff", buf.read(20))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if doxygen_t in parents: return 0
        tmphash = (0x6f08f01ca2b248d2) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if doxygen_t._packed_fingerprint is None:
            doxygen_t._packed_fingerprint = struct.pack(">Q", doxygen_t._get_hash_recursive([]))
        return doxygen_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

