"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class finishSim_t(object):
    __slots__ = ["length", "T", "xRobotx", "xRoboty"]

    def __init__(self):
        self.length = 0
        self.T = []
        self.xRobotx = []
        self.xRoboty = []

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(finishSim_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">h", self.length))
        buf.write(struct.pack('>%df' % self.length, *self.T[:self.length]))
        buf.write(struct.pack('>%df' % self.length, *self.xRobotx[:self.length]))
        buf.write(struct.pack('>%df' % self.length, *self.xRoboty[:self.length]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != finishSim_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return finishSim_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = finishSim_t()
        self.length = struct.unpack(">h", buf.read(2))[0]
        self.T = struct.unpack('>%df' % self.length, buf.read(self.length * 4))
        self.xRobotx = struct.unpack('>%df' % self.length, buf.read(self.length * 4))
        self.xRoboty = struct.unpack('>%df' % self.length, buf.read(self.length * 4))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if finishSim_t in parents: return 0
        tmphash = (0x3cdd8c8a29558cb3) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if finishSim_t._packed_fingerprint is None:
            finishSim_t._packed_fingerprint = struct.pack(">Q", finishSim_t._get_hash_recursive([]))
        return finishSim_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

