"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class ibps_opow_t(object):
    __slots__ = ["utime", "nbatt", "ncurr", "current", "power", "amphours", "watthours", "avgcharge", "state"]

    def __init__(self):
        self.utime = 0
        self.nbatt = 0
        self.ncurr = 0
        self.current = 0.0
        self.power = 0.0
        self.amphours = 0.0
        self.watthours = 0.0
        self.avgcharge = 0.0
        self.state = 0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(ibps_opow_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qhhfffffB", self.utime, self.nbatt, self.ncurr, self.current, self.power, self.amphours, self.watthours, self.avgcharge, self.state))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != ibps_opow_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ibps_opow_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ibps_opow_t()
        self.utime, self.nbatt, self.ncurr, self.current, self.power, self.amphours, self.watthours, self.avgcharge, self.state = struct.unpack(">qhhfffffB", buf.read(33))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ibps_opow_t in parents: return 0
        tmphash = (0xa934b8a4057e5d0c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ibps_opow_t._packed_fingerprint is None:
            ibps_opow_t._packed_fingerprint = struct.pack(">Q", ibps_opow_t._get_hash_recursive([]))
        return ibps_opow_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

