"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class ibps_cntrl_t(object):
    __slots__ = ["utime", "cntrl_id", "present", "charging", "supplying_pwr", "charge_pwr_present", "pwr_no_good", "charge_inhibited"]

    def __init__(self):
        self.utime = 0
        self.cntrl_id = 0
        self.present = 0
        self.charging = 0
        self.supplying_pwr = 0
        self.charge_pwr_present = 0
        self.pwr_no_good = 0
        self.charge_inhibited = 0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(ibps_cntrl_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qhbbbbbb", self.utime, self.cntrl_id, self.present, self.charging, self.supplying_pwr, self.charge_pwr_present, self.pwr_no_good, self.charge_inhibited))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != ibps_cntrl_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ibps_cntrl_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ibps_cntrl_t()
        self.utime, self.cntrl_id, self.present, self.charging, self.supplying_pwr, self.charge_pwr_present, self.pwr_no_good, self.charge_inhibited = struct.unpack(">qhbbbbbb", buf.read(16))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ibps_cntrl_t in parents: return 0
        tmphash = (0xfe23054ba94cfdf0) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ibps_cntrl_t._packed_fingerprint is None:
            ibps_cntrl_t._packed_fingerprint = struct.pack(">Q", ibps_cntrl_t._get_hash_recursive([]))
        return ibps_cntrl_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

