"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class imu_45_ahrs_t(object):
    __slots__ = ["utime", "scaled_accel", "scaled_gyro", "roll", "pitch", "yaw"]

    def __init__(self):
        self.utime = 0
        self.scaled_accel = [ 0.0 for dim0 in range(3) ]
        self.scaled_gyro = [ 0.0 for dim0 in range(3) ]
        self.roll = 0.0
        self.pitch = 0.0
        self.yaw = 0.0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(imu_45_ahrs_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(struct.pack('>3f', *self.scaled_accel[:3]))
        buf.write(struct.pack('>3f', *self.scaled_gyro[:3]))
        buf.write(struct.pack(">fff", self.roll, self.pitch, self.yaw))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != imu_45_ahrs_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return imu_45_ahrs_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = imu_45_ahrs_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.scaled_accel = struct.unpack('>3f', buf.read(12))
        self.scaled_gyro = struct.unpack('>3f', buf.read(12))
        self.roll, self.pitch, self.yaw = struct.unpack(">fff", buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if imu_45_ahrs_t in parents: return 0
        tmphash = (0xa54a4f1847a5f47b) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if imu_45_ahrs_t._packed_fingerprint is None:
            imu_45_ahrs_t._packed_fingerprint = struct.pack(">Q", imu_45_ahrs_t._get_hash_recursive([]))
        return imu_45_ahrs_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

