"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class relay_resp_t(object):
    __slots__ = ["utime", "relayA", "relayB"]

    def __init__(self):
        self.utime = 0
        self.relayA = 0
        self.relayB = 0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(relay_resp_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qbb", self.utime, self.relayA, self.relayB))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != relay_resp_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return relay_resp_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = relay_resp_t()
        self.utime, self.relayA, self.relayB = struct.unpack(">qbb", buf.read(10))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if relay_resp_t in parents: return 0
        tmphash = (0xc8162e2001a99cf2) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if relay_resp_t._packed_fingerprint is None:
            relay_resp_t._packed_fingerprint = struct.pack(">Q", relay_resp_t._get_hash_recursive([]))
        return relay_resp_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

