"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class sonardyne_page_t(object):
    __slots__ = ["utime", "page", "good_counts"]

    def __init__(self):
        self.utime = 0
        self.page = [ 0 for dim0 in range(512) ]
        self.good_counts = 0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(sonardyne_page_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(self.page[:512])
        buf.write(struct.pack(">q", self.good_counts))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != sonardyne_page_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return sonardyne_page_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = sonardyne_page_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.page = buf.read(512)
        self.good_counts = struct.unpack(">q", buf.read(8))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if sonardyne_page_t in parents: return 0
        tmphash = (0x7593c5d80839bcc6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if sonardyne_page_t._packed_fingerprint is None:
            sonardyne_page_t._packed_fingerprint = struct.pack(">Q", sonardyne_page_t._get_hash_recursive([]))
        return sonardyne_page_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

