"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class ubms_charge_t(object):
    __slots__ = ["utime", "current_setpoint", "voltage_setpoint", "end_of_charge", "interbalance_req_num"]

    def __init__(self):
        self.utime = 0
        self.current_setpoint = 0
        self.voltage_setpoint = 0
        self.end_of_charge = False
        self.interbalance_req_num = 0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(ubms_charge_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qhibh", self.utime, self.current_setpoint, self.voltage_setpoint, self.end_of_charge, self.interbalance_req_num))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != ubms_charge_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ubms_charge_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ubms_charge_t()
        self.utime, self.current_setpoint, self.voltage_setpoint, self.end_of_charge, self.interbalance_req_num = struct.unpack(">qhibh", buf.read(17))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ubms_charge_t in parents: return 0
        tmphash = (0x9b51e573327ac86e) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ubms_charge_t._packed_fingerprint is None:
            ubms_charge_t._packed_fingerprint = struct.pack(">Q", ubms_charge_t._get_hash_recursive([]))
        return ubms_charge_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

